"""init schema

Revision ID: bfc358b0322e
Revises: 
Create Date: 2026-03-20 22:09:24.200045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfc358b0322e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capability_registry',
    sa.Column('type', sa.Enum('MODEL', 'SKILL', 'MCP', 'FUNCTION', name='capabilitytype', native_enum=False), nullable=False),
    sa.Column('scope', sa.Enum('GLOBAL', 'LOCAL', name='capabilityscope', native_enum=False), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('config_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capability_registry_code'), 'capability_registry', ['code'], unique=True)
    op.create_table('task_template',
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='templatestatus', native_enum=False), nullable=False),
    sa.Column('latest_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_template_code'), 'task_template', ['code'], unique=True)
    op.create_table('task_template_version',
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='templatestatus', native_enum=False), nullable=False),
    sa.Column('definition_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['task_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'version', name='uq_template_version')
    )
    op.create_index(op.f('ix_task_template_version_template_id'), 'task_template_version', ['template_id'], unique=False)
    op.create_table('task_node',
    sa.Column('template_version_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.Enum('SYNC', 'ASYNC', name='nodemode', native_enum=False), nullable=False),
    sa.Column('executor', sa.Enum('AGENT', 'DIRECT', name='nodeexecutortype', native_enum=False), nullable=False),
    sa.Column('config_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_version_id'], ['task_template_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_version_id', 'code', name='uq_template_node_code'),
    sa.UniqueConstraint('template_version_id', 'seq', name='uq_template_node_seq')
    )
    op.create_index(op.f('ix_task_node_template_version_id'), 'task_node', ['template_version_id'], unique=False)
    op.create_table('task_run',
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('template_version_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'WAITING', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskrunstatus', native_enum=False), nullable=False),
    sa.Column('current_seq', sa.Integer(), nullable=True),
    sa.Column('input_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('context_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('output_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['task_template.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_version_id'], ['task_template_version.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id')
    )
    op.create_index(op.f('ix_task_run_template_id'), 'task_run', ['template_id'], unique=False)
    op.create_index(op.f('ix_task_run_template_version_id'), 'task_run', ['template_version_id'], unique=False)
    op.create_table('node_run',
    sa.Column('task_run_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'WAITING_CALLBACK', 'COMPLETED', 'FAILED', 'TIMEOUT', 'CANCELLED', name='noderunstatus', native_enum=False), nullable=False),
    sa.Column('wake_type', sa.Enum('EXTERNAL', 'TIMEOUT', name='waketype', native_enum=False), nullable=True),
    sa.Column('compensation_status', sa.Enum('NONE', 'PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', name='compensationstatus', native_enum=False), nullable=False),
    sa.Column('input_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('output_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('callback_payload_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('external_instance_id', sa.String(length=255), nullable=True),
    sa.Column('timeout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['task_node.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_run_id', 'seq', name='uq_node_run_seq')
    )
    op.create_index(op.f('ix_node_run_external_instance_id'), 'node_run', ['external_instance_id'], unique=False)
    op.create_index(op.f('ix_node_run_node_id'), 'node_run', ['node_id'], unique=False)
    op.create_index(op.f('ix_node_run_task_run_id'), 'node_run', ['task_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_run_task_run_id'), table_name='node_run')
    op.drop_index(op.f('ix_node_run_node_id'), table_name='node_run')
    op.drop_index(op.f('ix_node_run_external_instance_id'), table_name='node_run')
    op.drop_table('node_run')
    op.drop_index(op.f('ix_task_run_template_version_id'), table_name='task_run')
    op.drop_index(op.f('ix_task_run_template_id'), table_name='task_run')
    op.drop_table('task_run')
    op.drop_index(op.f('ix_task_node_template_version_id'), table_name='task_node')
    op.drop_table('task_node')
    op.drop_index(op.f('ix_task_template_version_template_id'), table_name='task_template_version')
    op.drop_table('task_template_version')
    op.drop_index(op.f('ix_task_template_code'), table_name='task_template')
    op.drop_table('task_template')
    op.drop_index(op.f('ix_capability_registry_code'), table_name='capability_registry')
    op.drop_table('capability_registry')
    # ### end Alembic commands ###
